### ISSUE TITLE
Project missing a spicy description

### ISSUE THREAD

**Issue by ckartik** [DougAnderson444/svelte-fillvert#1]
Noticed the project is missing a description in the image attached below.
![Screen Shot 2022-09-22 at 12 20 53 AM](https://user-images.githubusercontent.com/13803371/191657824-667b03a5-200e-4683-bf1e-25f4757d8f1d.png)

Would be interesting to add a topic as well!

**Comment by DougAnderson444** [comment]
Spiciness added :) thank you!
